require('dotenv').config()
require('./server/db-conn');
const express = require('express')
const bodyParser = require('body-parser')

const app = express()

app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:false}))
//gives server access to static files generated by running yarn build in client
app.use(express.static('./client/myazurereact/build/')); 

//mount routers
app.use('/api/articles/', require('./server/routes/articles-route'));

app.get('/*', (req, res)=>{
    res.sendFile('index.html', {root:__dirname + '/client/myazurereact/build/'});
});

const {PORT} = process.env;
app.listen(PORT,()=> console.log(`The server started on port ${PORT}`))

